[package]
name = "esripbf"
version = "0.1.0"
edition = "2021"
exclude = ["create-proto.rs"]

[dependencies]
bytes = "1.5.0"
extendr-api = "0.6.0"
geo-types = "0.7.11"
itertools = "0.11.0"
prost = "0.12.1"

# [build-dependencies]
# prost-build = "0.12.1"

