on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Fedora R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/valgrind:latest

    name: Fedora R CMD check

    strategy:
      fail-fast: false

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'
